/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "mapTypeTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid mapTypeTable_oid[] = {mapTypeTable_TABLE_OID};
const size_t mapTypeTable_oid_len = OID_LENGTH(mapTypeTable_oid);

/*This function will return the table with a certain id*/
mapTypeTable_context *findRow(unsigned long id)
{
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = id;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    void *data = CONTAINER_FIND(cb.container, &index);
    mapTypeTable_context *mapType = data;
    return mapType;
}

#ifdef mapTypeTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int mapTypeTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
mapTypeTable_cmp(const void *lhs, const void *rhs)
{
    mapTypeTable_context *context_l =
        (mapTypeTable_context *)lhs;
    mapTypeTable_context *context_r =
        (mapTypeTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "mapTypeTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
mapTypeTable_context *
mapTypeTable_get(const char *name, int len)
{
    mapTypeTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "mapTypeTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the mapTypeTable module
 */
void init_mapTypeTable(BO_List *boList)
{
    mapTypeTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];

    sampleUnitsList sampleunitsList;
    sampleunitsList.capacity = 1;
    sampleunitsList.current = 0;
    sampleunitsList.list = malloc(sizeof(sampleUnitsStruct));

    genericTypeList typesList;
    typesList.capacity = 1;
    typesList.current = 0;
    typesList.genericList = malloc(sizeof(genericTypeList));
    initialize_table_mapTypeTable();
    int inserted = 0;
    int errorInserted = 0;
    regex_t regex;
    int value = regcomp(&regex, "DM[0-9]+:", REG_EXTENDED);
    if (value)
    {
        fprintf(stderr, "Could not compile regex\n");
        exit(1);
    }
    for (int i = 0; i < boList->current; i++)
    {
        value = regexec(&regex, boList->list[i].name, 0, NULL, 0);
        if (value == REG_NOMATCH)
        {
            for (int j = 0; j < boList->list[i].signals->current; j++)
            {
                int idSampleUnits = addToSampleUnits(&sampleunitsList, boList->list[i].messageID, boList->list[i].signals->list[j].unit);
                int idGenericTypes = addToGenericTypes(&typesList, boList->list[i].messageID, boList->list[i].signals->list[j].description);
                index_oid[0] = inserted;
                index.oids = (oid *)&index_oid;
                index.len = 1;
                char *aux = malloc(sizeof(char) + strlen(boList->list[i].signals->list[j].name) + strlen(boList->list[i].name) + 1);
                strcpy(aux, boList->list[i].name);
                strcat(aux, boList->list[i].signals->list[j].name);
                ctx = NULL;
                /* Search for it first. */
                ctx = CONTAINER_FIND(cb.container, &index);
                if (!ctx)
                {
                    // No dice. We add the new row
                    ctx = mapTypeTable_create_row(&index, aux, "CAN 2.0", inserted, idGenericTypes, idSampleUnits, 0, 0, 0, 0);
                    CONTAINER_INSERT(cb.container, ctx);
                    inserted++;
                }
                free(aux);
            }
        }
    }
    init_sampleUnitsTable(&sampleunitsList);
    init_genericTypesTable(&typesList);
    regfree(&regex);
}

/************************************************************
 *
 * Initialize the mapTypeTable table by defining its contents and how it's structured
 */
void initialize_table_mapTypeTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_mapTypeTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("mapTypeTable",
                                                     netsnmp_table_array_helper_handler,
                                                     mapTypeTable_oid,
                                                     mapTypeTable_oid_len,
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_mapTypeTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: mapTypeID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = mapTypeTable_COL_MIN;
    table_info->max_column = mapTypeTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = mapTypeTable_get_value;
    cb.container = netsnmp_container_find("mapTypeTable_primary:"
                                          "mapTypeTable:"
                                          "table_container");
#ifdef mapTypeTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("mapTypeTable_custom:"
                                                       "mapTypeTable:"
                                                       "table_container"));
    cb.container->next->compare = mapTypeTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_mapTypeTable",
                "Registering table mapTypeTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * mapTypeTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int mapTypeTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    mapTypeTable_context *context = (mapTypeTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_MAPTYPEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->mapTypeID,
                                 sizeof(context->mapTypeID));
        break;

    case COLUMN_PROPRIETARYTYPEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->proprietaryTypeID,
                                 sizeof(context->proprietaryTypeID));
        break;

    case COLUMN_GENERICMAPTYPEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->genericMapTypeID,
                                 sizeof(context->genericMapTypeID));
        break;

    case COLUMN_SAMPLEUNITMAPID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->sampleUnitMapID,
                                 sizeof(context->sampleUnitMapID));
        break;

    case COLUMN_PRECISION:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->precision,
                                 sizeof(context->precision));
        break;

    case COLUMN_MAXSAMPLINGFREQUENCY:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->maxSamplingFrequency,
                                 sizeof(context->maxSamplingFrequency));
        break;

    case COLUMN_MAXMAPDELAY:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->maxMapDelay,
                                 sizeof(context->maxMapDelay));
        break;

    case COLUMN_DATASOURCE:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->dataSource,
                                 context->dataSource_len);
        break;

    case COLUMN_INTERFACESOURCE:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->interfaceSource,
                                 context->interfaceSource_len);
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "mapTypeTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * mapTypeTable_get_by_idx
 */
const mapTypeTable_context *
mapTypeTable_get_by_idx(netsnmp_index *hdr)
{
    return (const mapTypeTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated mapTypeTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
mapTypeTable_context *mapTypeTable_create_row(netsnmp_index *hdr, char *data, char *interface, int id, int generic, int sampleunit, int proprietary,
                                              int precision, int maxsample, int maxdelay)
{
    mapTypeTable_context *ctx = SNMP_MALLOC_TYPEDEF(mapTypeTable_context);
    if (!ctx)
        return NULL;
    if (mapTypeTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = id;
    ctx->index.len = 1;
    ctx->mapTypeID = (long unsigned int)id;
    ctx->genericMapTypeID = generic;
    ctx->sampleUnitMapID = sampleunit;
    ctx->proprietaryTypeID = proprietary;
    ctx->precision = precision;
    ctx->maxSamplingFrequency = maxsample;
    ctx->maxMapDelay = maxdelay;
    strcpy(ctx->dataSource, data);
    ctx->dataSource_len = strlen(data);
    strcpy(ctx->interfaceSource, interface);
    ctx->interfaceSource_len = strlen(interface);
    return ctx;
}

/*
 * the *_extract_index routine
 */
int mapTypeTable_extract_index(mapTypeTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_mapTypeID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if (snmp_clone_mem((void *)&ctx->index.oids, hdr->oids, sizeof(oid)))
        {
            return -1;
        }
    }

    /**
     * Create variable to hold each component of the index
     */
    memset(&var_mapTypeID, 0x00, sizeof(var_mapTypeID));
    var_mapTypeID.type = ASN_GAUGE;
    /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "mapTypeTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_mapTypeID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_mapTypeID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy components into the context structure
        */
        /** skipping external index mapTypeID */
        if (var_mapTypeID.val_len > sizeof(ctx->mapTypeID))
            err = -1;
        else
            ctx->mapTypeID = (long unsigned int)var_mapTypeID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( XXX_check_value( var_mapTypeID.val, XXX ) ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_mapTypeID);

    return err;
}
/************************************************************
 * the *_duplicate row routine
 */
mapTypeTable_context *mapTypeTable_duplicate_row(mapTypeTable_context *row_ctx)
{
    mapTypeTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(mapTypeTable_context);
    if (!dup)
        return NULL;

    if (mapTypeTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}
/************************************************************
 * the *_row_copy routine
 */
int mapTypeTable_row_copy(mapTypeTable_context *dst, mapTypeTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    dst->mapTypeID = src->mapTypeID;
    dst->proprietaryTypeID = src->proprietaryTypeID;
    dst->genericMapTypeID = src->genericMapTypeID;
    dst->sampleUnitMapID = src->sampleUnitMapID;
    dst->precision = src->precision;
    dst->maxSamplingFrequency = src->maxSamplingFrequency;
    dst->maxMapDelay = src->maxMapDelay;

    memcpy(dst->dataSource, src->dataSource, src->dataSource_len);
    dst->dataSource_len = src->dataSource_len;
    memcpy(dst->interfaceSource, src->interfaceSource, src->interfaceSource_len);
    dst->interfaceSource_len = src->interfaceSource_len;
    return 0;
}