/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "errorTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid errorTable_oid[] = {errorTable_TABLE_OID};
const size_t errorTable_oid_len = OID_LENGTH(errorTable_oid);
/*This function will delete an entry from errorTable*/
int deleteErrorEntry(long unsigned int id)
{
    errorTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = id;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
    {
        CONTAINER_REMOVE(cb.container, &index);
        errorTable_delete_row(ctx);
    }
    else
    {
        return 2;
    }
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
        return 1;
    else
        return 0;
}
/*This function will check every entry on errorTable and delete the entries whose expireTime has past*/
void checkError()
{
    netsnmp_iterator *it;
    void *data;
    it = CONTAINER_ITERATOR(cb.container);
    if (NULL == it)
    {
        exit(0);
    }
    for (data = ITERATOR_FIRST(it); data; data = ITERATOR_NEXT(it))
    {
        errorTable_context *req = data;
        time_t t = time(NULL);
        struct tm *tm = localtime(&t);
        struct tm *tm2 = (struct tm *)malloc(sizeof(struct tm));
        char *timestamp = malloc(sizeof(char) * req->errorTimeStamp_len + 1);
        strcpy(timestamp, req->errorTimeStamp);
        tm2 = convertTime(tm2, timestamp);

        char *hour = malloc(sizeof(char) * 3);
        char *min = malloc(sizeof(char) * 3);
        strncpy(hour, req->errorExpireTime, 2);
        strncpy(min, req->errorExpireTime + 3, 2);
        min[2] = '\0';
        hour[2] = '\0';
        tm2 = addToTime(tm2, atoi(hour), atoi(min));
        if (compareTimeStamp(tm, tm2) != 1)
        {
            /*ExpireTime has passed, delete row*/
            int delete = deleteErrorEntry(req->errorID);
            if (delete == 1)
                printf("Error entry deletion failed: %ld\n", req->errorID);
            else if (delete == 2)
                printf("Error entry not found: %ld\n", req->errorID);
        }
        free(min);
        free(hour);
        free(tm2);
        free(timestamp);
    }
    ITERATOR_RELEASE(it);
}
/*This function will return the first empty ID of errorTable*/
int firstErrorEntry()
{
    netsnmp_iterator *it;
    void *data;
    it = CONTAINER_ITERATOR(cb.container);
    int res = 0;
    if (NULL == it)
    {
        return res;
    }
    for (data = ITERATOR_FIRST(it); data; data = ITERATOR_NEXT(it))
    {
        errorTable_context *req = data;
        if (req != NULL)
            res = req->errorID + 1;
    }
    ITERATOR_RELEASE(it);
    return res;
}
/*This function will add an error to errorTable*/
int addError(char *user, int id)
{
    errorTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    errorStruct *req = (errorStruct *)malloc(sizeof(errorStruct));
    req->errorID = firstErrorEntry();
    time_t t = time(NULL);
    struct tm *tm = localtime(&t);
    char s[100];
    snprintf(s, 100, "%02d/%02d/%04d %02d:%02d:%02d", tm->tm_mday, tm->tm_mon + 1, tm->tm_year + 1900, tm->tm_hour, tm->tm_min, tm->tm_sec);
    req->errorTimeStamp = malloc(sizeof(char) * strlen(s));
    strcpy(req->errorTimeStamp, s);
    req->errorDescriptionID = id;
    req->errorUser = malloc(sizeof(char) * strlen(user) + 1);
    strcpy(req->errorUser, user);
    req->errorExpireTime = "00:01:00";
    index_oid[0] = req->errorID;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (!ctx)
    {
        // No dice. We add the new row
        ctx = errorTable_create_row(&index, req);
        CONTAINER_INSERT(cb.container, ctx);
        free(req);
    }
    else
    {
        free(req);
        return 1;
    }
    return 0;
}

#ifdef errorTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int errorTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
errorTable_cmp(const void *lhs, const void *rhs)
{
    errorTable_context *context_l =
        (errorTable_context *)lhs;
    errorTable_context *context_r =
        (errorTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "errorTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
errorTable_context *
errorTable_get(const char *name, int len)
{
    errorTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "errorTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the errorTable module
 */
void init_errorTable(void)
{
    initialize_table_errorTable();
}

/************************************************************
 * the *_row_copy routine
 */
int errorTable_row_copy(errorTable_context *dst,
                        errorTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;

    /*
     * copy components into the context structure
     */
    dst->errorID = src->errorID;

    memcpy(dst->errorTimeStamp, src->errorTimeStamp, src->errorTimeStamp_len);
    dst->errorTimeStamp_len = src->errorTimeStamp_len;

    dst->errorDescriptionID = src->errorDescriptionID;

    memcpy(dst->errorTimeStamp, src->errorTimeStamp, src->errorTimeStamp_len);
    dst->errorTimeStamp_len = src->errorTimeStamp_len;

    memcpy(dst->errorUser, src->errorUser, src->errorUser_len);
    dst->errorUser_len = src->errorUser_len;

    memcpy(dst->errorExpireTime, src->errorExpireTime, src->errorExpireTime_len);
    dst->errorExpireTime_len = src->errorExpireTime_len;

    return 0;
}

/**
 * the *_extract_index routine
 *
 * This routine is called when a set request is received for an index
 * that was not found in the table container. Here, we parse the oid
 * in the the individual index components and copy those indexes to the
 * context. Then we make sure the indexes for the new row are valid.
 */
int errorTable_extract_index(errorTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     *
     * extract index uses varbinds (netsnmp_variable_list) to parse
     * the index OID into the individual components for each index part.
     */
    netsnmp_variable_list var_errorID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if ((hdr->len > MAX_OID_LEN) ||
            snmp_clone_mem((void *)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid)))
        {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /*
     * initialize variable that will hold each component of the index.
     * If there are multiple indexes for the table, the variable_lists
     * need to be linked together, in order.
     */
    memset(&var_errorID, 0x00, sizeof(var_errorID));
    var_errorID.type = ASN_UNSIGNED; /* type hint for parse_oid_indexes */
                                     /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "errorTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_errorID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_errorID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy index components into the context structure
        */
        ctx->errorID = *var_errorID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_errorID.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_errorID);

    return err;
}

/************************************************************
 * the *_can_delete routine is called to determine if a row
 * can be deleted.
 *
 * return 1 if the row can be deleted
 * return 0 if the row cannot be deleted
 */
int errorTable_can_delete(errorTable_context *undo_ctx,
                          errorTable_context *row_ctx,
                          netsnmp_request_group *rg)
{

    /*
     * TODO: check for other deletion requirements here
     */
    return 1;
}

/************************************************************
 * the *_duplicate row routine
 */
errorTable_context *
errorTable_duplicate_row(errorTable_context *row_ctx)
{
    errorTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(errorTable_context);
    if (!dup)
        return NULL;

    if (errorTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}

/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index *errorTable_delete_row(errorTable_context *ctx)
{
    /* netsnmp_mutex_destroy(ctx->lock); */
    /*
    if (ctx->index.oids)
        free(ctx->index.oids);
    */
    free(ctx->data);

    /*
     * release header
     */
    free(ctx);

    return NULL;
}

/************************************************************
 * RESERVE is used to check the syntax of all the variables
 * provided, that the values being set are sensible and consistent,
 * and to allocate any resources required for performing the SET.
 * After this stage, the expectation is that the set ought to
 * succeed, though this is not guaranteed. (In fact, with the UCD
 * agent, this is done in two passes - RESERVE1, and
 * RESERVE2, to allow for dependancies between variables).
 *
 * BEFORE calling this routine, the agent will call duplicate_row
 * to create a copy of the row (unless this is a new row; i.e.
 * row_created == 1).
 *
 * next state -> SET_RESERVE2 || SET_FREE
 */
void errorTable_set_reserve1(netsnmp_request_group *rg)
{
    errorTable_context *row_ctx =
        (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx =
        (errorTable_context *)rg->undo_info;
    netsnmp_variable_list *var;
    netsnmp_request_group_item *current;
    int rc;

    /*
     * TODO: loop through columns, check syntax and lengths. For
     * columns which have no dependencies, you could also move
     * the value/range checking here to attempt to catch error
     * cases as early as possible.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /* or possibly 'netsnmp_check_vb_int_range' */
            rc = netsnmp_check_vb_int(var);
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            /* or possibly 'netsnmp_check_vb_type_and_size' */
            rc = netsnmp_check_vb_type_and_max_size(var, ASN_OCTET_STR,
                                                    sizeof(row_ctx->errorTimeStamp));
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /* or possibly 'netsnmp_check_vb_int_range' */
            rc = netsnmp_check_vb_int(var);
            break;
        case COLUMN_ERRORUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            /* or possibly 'netsnmp_check_vb_type_and_size' */
            rc = netsnmp_check_vb_type_and_max_size(var, ASN_OCTET_STR,
                                                    sizeof(row_ctx->errorUser));
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OCTET STRING = ASN_OCTET_STR */
            /* or possibly 'netsnmp_check_vb_type_and_size' */
            rc = netsnmp_check_vb_type_and_max_size(var, ASN_OCTET_STR,
                                                    sizeof(row_ctx->errorExpireTime));
            break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column in "
                              "errorTable_set_reserve1\n");
        }

        if (rc)
            netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
        rg->status = SNMP_MAX(rg->status, current->ri->status);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

void errorTable_set_reserve2(netsnmp_request_group *rg)
{
    errorTable_context *row_ctx = (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx = (errorTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    netsnmp_variable_list *var;
    int rc;

    rg->rg_void = rg->list->ri;

    /*
     * TODO: loop through columns, check for valid
     * values and any range constraints.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;

        case COLUMN_ERRORUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OCTET STRING = ASN_OCTET_STR */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;
        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }

        if (rc)
            netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * Assuming that the RESERVE phases were successful, the next
 * stage is indicated by the action value ACTION. This is used
 * to actually implement the set operation. However, this must
 * either be done into temporary (persistent) storage, or the
 * previous value stored similarly, in case any of the subsequent
 * ACTION calls fail.
 *
 * In your case, changes should be made to row_ctx. A copy of
 * the original row is in undo_ctx.
 */
void errorTable_set_action(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    errorTable_context *row_ctx = (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx = (errorTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * TODO: loop through columns, copy varbind values
     * to context structure for the row.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            row_ctx->errorID = *var->val.integer;
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            memcpy(row_ctx->errorTimeStamp, var->val.string, var->val_len);
            row_ctx->errorTimeStamp_len = var->val_len;
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            row_ctx->errorDescriptionID = *var->val.integer;
            break;

        case COLUMN_ERRORUSER:
            /** OBUDateandTime = ASN_OCTET_STR */
            memcpy(row_ctx->errorUser, var->val.string, var->val_len);
            row_ctx->errorUser_len = var->val_len;
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OBUDateandTime = ASN_OCTET_STR */
            memcpy(row_ctx->errorExpireTime, var->val.string, var->val_len);
            row_ctx->errorExpireTime_len = var->val_len;
            break;

        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
    /*
     * TODO: if you have dependencies on other tables, this would be
     * a good place to check those, too.
     */
}

/************************************************************
 * Only once the ACTION phase has completed successfully, can
 * the final COMMIT phase be run. This is used to complete any
 * writes that were done into temporary storage, and then release
 * any allocated resources. Note that all the code in this phase
 * should be "safe" code that cannot possibly fail (cue
 * hysterical laughter). The whole intent of the ACTION/COMMIT
 * division is that all of the fallible code should be done in
 * the ACTION phase, so that it can be backed out if necessary.
 *
 * BEFORE calling this routine, the agent will update the
 * container (inserting a row if row_created == 1, or removing
 * the row if row_deleted == 1).
 *
 * AFTER calling this routine, the agent will delete the
 * undo_info.
 */
void errorTable_set_commit(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    errorTable_context *row_ctx = (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx = (errorTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If either of the RESERVE calls fail, the write routines
 * are called again with the FREE action, to release any resources
 * that have been allocated. The agent will then return a failure
 * response to the requesting application.
 *
 * AFTER calling this routine, the agent will delete undo_info.
 */
void errorTable_set_free(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    errorTable_context *row_ctx = (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx = (errorTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        default: /** We shouldn't get here */
            break;
            /** should have been logged in reserve1 */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If the ACTION phase does fail (for example due to an apparently
 * valid, but unacceptable value, or an unforeseen problem), then
 * the list of write routines are called again, with the UNDO
 * action. This requires the routine to reset the value that was
 * changed to its previous value (assuming it was actually changed),
 * and then to release any resources that had been allocated. As
 * with the FREE phase, the agent will then return an indication
 * of the error to the requesting application.
 *
 * BEFORE calling this routine, the agent will update the container
 * (remove any newly inserted row, re-insert any removed row).
 *
 * AFTER calling this routing, the agent will call row_copy
 * to restore the data in existing_row from the date in undo_info.
 * Then undo_info will be deleted (or existing row, if row_created
 * == 1).
 */
void errorTable_set_undo(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    errorTable_context *row_ctx = (errorTable_context *)rg->existing_row;
    errorTable_context *undo_ctx = (errorTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_ERRORID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORTIMESTAMP:
            /** OBUDateandTime = ASN_OCTET_STR */
            break;

        case COLUMN_ERRORDESCRIPTIONID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_ERRORUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        case COLUMN_ERROREXPIRETIME:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 *
 * Initialize the errorTable table by defining its contents and how it's structured
 */
void initialize_table_errorTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_errorTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("errorTable",
                                                     netsnmp_table_array_helper_handler,
                                                     errorTable_oid,
                                                     errorTable_oid_len,
                                                     HANDLER_CAN_RWRITE);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_errorTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: errorID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = errorTable_COL_MIN;
    table_info->max_column = errorTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = errorTable_get_value;
    cb.container = netsnmp_container_find("errorTable_primary:"
                                          "errorTable:"
                                          "table_container");
#ifdef errorTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("errorTable_custom:"
                                                       "errorTable:"
                                                       "table_container"));
    cb.container->next->compare = errorTable_cmp;
#endif
    cb.can_set = 1;
    cb.duplicate_row = (UserRowMethod *)errorTable_duplicate_row;
    cb.delete_row = (UserRowMethod *)errorTable_delete_row;
    cb.row_copy = (Netsnmp_User_Row_Operation *)errorTable_row_copy;

    cb.can_delete = (Netsnmp_User_Row_Action *)errorTable_can_delete;

    cb.set_reserve1 = errorTable_set_reserve1;
    cb.set_reserve2 = errorTable_set_reserve2;
    cb.set_action = errorTable_set_action;
    cb.set_commit = errorTable_set_commit;
    cb.set_free = errorTable_set_free;
    cb.set_undo = errorTable_set_undo;
    DEBUGMSGTL(("initialize_table_errorTable",
                "Registering table errorTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * errorTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int errorTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    errorTable_context *context = (errorTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_ERRORID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->errorID,
                                 sizeof(context->errorID));
        break;

    case COLUMN_ERRORTIMESTAMP:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->errorTimeStamp,
                                 context->errorTimeStamp_len);
        break;

    case COLUMN_ERRORDESCRIPTIONID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->errorDescriptionID,
                                 sizeof(context->errorDescriptionID));
        break;

    case COLUMN_ERRORUSER:
        /** OCTET STRING = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->errorUser,
                                 context->errorUser_len);
        break;

    case COLUMN_ERROREXPIRETIME:
        /** OCTET STRING = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->errorExpireTime,
                                 context->errorExpireTime_len);
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "errorTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * errorTable_get_by_idx
 */
const errorTable_context *
errorTable_get_by_idx(netsnmp_index *hdr)
{
    return (const errorTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated errorTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
errorTable_context *errorTable_create_row(netsnmp_index *hdr, errorStruct *req)
{
    errorTable_context *ctx = SNMP_MALLOC_TYPEDEF(errorTable_context);
    if (!ctx)
        return NULL;
    if (errorTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = req->errorID;
    ctx->index.len = 1;
    ctx->errorID = (long unsigned int)req->errorID;
    strcpy(ctx->errorTimeStamp, req->errorTimeStamp);
    ctx->errorTimeStamp_len = strlen(req->errorTimeStamp);
    ctx->errorDescriptionID = (long unsigned int)req->errorDescriptionID;
    strcpy(ctx->errorUser, req->errorUser);
    ctx->errorUser_len = strlen(req->errorUser);
    strcpy(ctx->errorExpireTime, req->errorExpireTime);
    ctx->errorExpireTime_len = strlen(req->errorExpireTime);
    return ctx;
}
