/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "capabilitiesTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid capabilitiesTable_oid[] = {capabilitiesTable_TABLE_OID};
const size_t capabilitiesTable_oid_len = OID_LENGTH(capabilitiesTable_oid);

#ifdef capabilitiesTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int capabilitiesTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
capabilitiesTable_cmp(const void *lhs, const void *rhs)
{
    capabilitiesTable_context *context_l =
        (capabilitiesTable_context *)lhs;
    capabilitiesTable_context *context_r =
        (capabilitiesTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "capabilitiesTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
capabilitiesTable_context *
capabilitiesTable_get(const char *name, int len)
{
    capabilitiesTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "capabilitiesTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the capabilitiesTable module
 */
void init_capabilitiesTable(void)
{
    initialize_table_capabilitiesTable();
    char *cap[] = {"Teste1", "Teste2", "Teste3"};
    capabilitiesTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];

    for (int i = 0; i < sizeof(cap) / sizeof(cap[0]); i++)
    {
        index_oid[0] = i;
        index.oids = (oid *)&index_oid;
        index.len = 1;
        ctx = NULL;
        /* Search for it first. */
        ctx = CONTAINER_FIND(cb.container, &index);
        if (!ctx)
        {
            // No dice. We add the new row
            ctx = capabilitiesTable_create_row(&index, cap[i], i, i + 1, i + 2);
            CONTAINER_INSERT(cb.container, ctx);
        }
    }
}

/************************************************************
 *
 * Initialize the capabilitiesTable table by defining its contents and how it's structured
 */
void initialize_table_capabilitiesTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_capabilitiesTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("capabilitiesTable",
                                                     netsnmp_table_array_helper_handler,
                                                     capabilitiesTable_oid,
                                                     capabilitiesTable_oid_len,
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_capabilitiesTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: capabilitiesID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = capabilitiesTable_COL_MIN;
    table_info->max_column = capabilitiesTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = capabilitiesTable_get_value;
    cb.container = netsnmp_container_find("capabilitiesTable_primary:"
                                          "capabilitiesTable:"
                                          "table_container");
#ifdef capabilitiesTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("capabilitiesTable_custom:"
                                                       "capabilitiesTable:"
                                                       "table_container"));
    cb.container->next->compare = capabilitiesTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_capabilitiesTable",
                "Registering table capabilitiesTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * capabilitiesTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int capabilitiesTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    capabilitiesTable_context *context = (capabilitiesTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_CAPABILITIESID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->capabilitiesID,
                                 sizeof(context->capabilitiesID));
        break;

    case COLUMN_SETOFCAPABILITIESID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->setOfCapabilitiesID,
                                 sizeof(context->setOfCapabilitiesID));
        break;

    case COLUMN_SPECIFICCAPABILITIESID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->specificCapabilitiesID,
                                 sizeof(context->specificCapabilitiesID));
        break;

    case COLUMN_CAPABILITIEVALUE:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->capabilitieValue,
                                 context->capabilitieValue_len);
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "capabilitiesTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * capabilitiesTable_get_by_idx
 */
const capabilitiesTable_context *
capabilitiesTable_get_by_idx(netsnmp_index *hdr)
{
    return (const capabilitiesTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated capabilitiesTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
capabilitiesTable_context *capabilitiesTable_create_row(netsnmp_index *hdr, char *descr, int id, int a, int b)
{
    capabilitiesTable_context *ctx = SNMP_MALLOC_TYPEDEF(capabilitiesTable_context);
    if (!ctx)
        return NULL;
    if (capabilitiesTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = id;
    ctx->index.len = 1;
    ctx->capabilitiesID = (long unsigned int)id;
    ctx->setOfCapabilitiesID = a;
    ctx->specificCapabilitiesID = b;
    strcpy(ctx->capabilitieValue, descr);
    ctx->capabilitieValue_len = strlen(descr);
    printf("Capability inserida: %ld, Set: %ld, Specific: %ld, Value: %s\n", ctx->capabilitiesID, ctx->setOfCapabilitiesID, ctx->specificCapabilitiesID, ctx->capabilitieValue);
    return ctx;
}

/*
 * the *_extract_index routine
 */
int capabilitiesTable_extract_index(capabilitiesTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_capabilitiesID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if (snmp_clone_mem((void *)&ctx->index.oids, hdr->oids, sizeof(oid)))
        {
            return -1;
        }
    }

    /**
     * Create variable to hold each component of the index
     */
    memset(&var_capabilitiesID, 0x00, sizeof(var_capabilitiesID));
    var_capabilitiesID.type = ASN_GAUGE;
    /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "capabilitiesTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_capabilitiesID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_capabilitiesID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy components into the context structure
        */
        /** skipping external index capabilitiesID */
        if (var_capabilitiesID.val_len > sizeof(ctx->capabilitiesID))
            err = -1;
        else
            ctx->capabilitiesID = (long unsigned int)var_capabilitiesID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( XXX_check_value( var_capabilitiesID.val, XXX ) ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_capabilitiesID);

    return err;
}
/************************************************************
 * the *_duplicate row routine
 */
capabilitiesTable_context *
capabilitiesTable_duplicate_row(capabilitiesTable_context *row_ctx)
{
    capabilitiesTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(capabilitiesTable_context);
    if (!dup)
        return NULL;

    if (capabilitiesTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}
/************************************************************
 * the *_row_copy routine
 */
int capabilitiesTable_row_copy(capabilitiesTable_context *dst, capabilitiesTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    dst->capabilitiesID = src->capabilitiesID;
    dst->setOfCapabilitiesID = src->setOfCapabilitiesID;
    dst->specificCapabilitiesID = src->specificCapabilitiesID;
    memcpy(dst->capabilitieValue, src->capabilitieValue, src->capabilitieValue_len);
    dst->capabilitieValue_len = src->capabilitieValue_len;

    return 0;
}