/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef SAMPLEDVALUESTABLE_H
#define SAMPLEDVALUESTABLE_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

    /** Index sampledValueID is internal */
    typedef struct sampledStruct
    {
        int sampledValueID;
        int relatedSampleValue;
        int sampleType;
        int sampleRecordedValue;
        int nOfsampledValues;
        int mapTypeSamplesID;
    } sampledStruct;
    typedef struct sampledValuesTable_context_s
    {
        netsnmp_index index; /** THIS MUST BE FIRST!!! */
        oid oid_buf[2];
        unsigned long sampledValueID;     /** UNSIGNED32 = ASN_UNSIGNED */
        unsigned long relatedSampleValue; /** UNSIGNED32 = ASN_UNSIGNED */
        long sampleType;                  /** INTEGER = ASN_INTEGER */
        long sampleRecordedValue;         /** INTEGER = ASN_INTEGER */
        unsigned long nOfSampledValues;   /** UNSIGNED32 = ASN_UNSIGNED */
        unsigned long mapTypeSamplesID;   /** UNSIGNED32 = ASN_UNSIGNED */
        int valid;
        void *data;
    } sampledValuesTable_context;

    /*************************************************************
 * function declarations
 */
    void init_sampledValuesTable(void);
    void initialize_table_sampledValuesTable(void);
    const sampledValuesTable_context *sampledValuesTable_get_by_idx(netsnmp_index *);
    const sampledValuesTable_context *sampledValuesTable_get_by_idx_rs(netsnmp_index *,
                                                                       int row_status);
    int sampledValuesTable_get_value(netsnmp_request_info *, netsnmp_index *, netsnmp_table_request_info *);

    /*************************************************************
 * oid declarations
 */
    extern const oid sampledValuesTable_oid[];
    extern const size_t sampledValuesTable_oid_len;

#define sampledValuesTable_TABLE_OID 1, 3, 6, 1, 3, 8888, 9

/*************************************************************
 * column number definitions for table sampledValuesTable
 */
#define COLUMN_SAMPLEDVALUEID 1
#define COLUMN_RELATEDSAMPLEVALUE 2
#define COLUMN_SAMPLETYPE 3
#define COLUMN_SAMPLERECORDEDVALUE 4
#define COLUMN_NOFSAMPLEDVALUES 5
#define COLUMN_MAPTYPESAMPLESID 6
#define sampledValuesTable_COL_MIN 1
#define sampledValuesTable_COL_MAX 6

/* comment out the following line if you don't handle SET-REQUEST for sampledValuesTable */
#define sampledValuesTable_SET_HANDLING

/* comment out the following line if you can't create new rows */
#define sampledValuesTable_ROW_CREATION

    /* comment out the following line if you don't want the secondary index */
    /* #define sampledValuesTable_IDX2  */

#ifdef sampledValuesTable_SET_HANDLING

    int sampledValuesTable_extract_index(sampledValuesTable_context *ctx, netsnmp_index *hdr);

    void sampledValuesTable_set_reserve1(netsnmp_request_group *);
    void sampledValuesTable_set_reserve2(netsnmp_request_group *);
    void sampledValuesTable_set_action(netsnmp_request_group *);
    void sampledValuesTable_set_commit(netsnmp_request_group *);
    void sampledValuesTable_set_free(netsnmp_request_group *);
    void sampledValuesTable_set_undo(netsnmp_request_group *);
    int sampledValuesTable_row_copy(sampledValuesTable_context *, sampledValuesTable_context *);
    sampledValuesTable_context *sampledValuesTable_duplicate_row(sampledValuesTable_context *);
    netsnmp_index *sampledValuesTable_delete_row(sampledValuesTable_context *);

    int sampledValuesTable_can_delete(sampledValuesTable_context *undo_ctx,
                                      sampledValuesTable_context *row_ctx,
                                      netsnmp_request_group *rg);

#ifdef sampledValuesTable_ROW_CREATION
    sampledValuesTable_context *sampledValuesTable_create_row(netsnmp_index *, sampledStruct *);
#endif
#endif

#ifdef sampledValuesTable_IDX2
    sampledValuesTable_context *sampledValuesTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
}
#endif

#endif /** SAMPLEDVALUESTABLE_H */
