/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "sampledValuesTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid sampledValuesTable_oid[] = {sampledValuesTable_TABLE_OID};
const size_t sampledValuesTable_oid_len = OID_LENGTH(sampledValuesTable_oid);

#ifdef sampledValuesTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int sampledValuesTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
sampledValuesTable_cmp(const void *lhs, const void *rhs)
{
    sampledValuesTable_context *context_l =
        (sampledValuesTable_context *)lhs;
    sampledValuesTable_context *context_r =
        (sampledValuesTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "sampledValuesTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
sampledValuesTable_context *
sampledValuesTable_get(const char *name, int len)
{
    sampledValuesTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "sampledValuesTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the sampledValuesTable module
 */
void init_sampledValuesTable(void)
{
    sampledValuesTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    initialize_table_sampledValuesTable();
    sampledStruct *req = (sampledStruct *)malloc(sizeof(sampledStruct));
    req->sampledValueID = 0;
    req->relatedSampleValue = 0;
    req->sampleType = 1;
    req->sampleRecordedValue = 120;
    req->nOfsampledValues = 1;
    index_oid[0] = 0;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (!ctx)
    {
        // No dice. We add the new row
        ctx = sampledValuesTable_create_row(&index, req);
        CONTAINER_INSERT(cb.container, ctx);
    }
}

/************************************************************
 *
 * Initialize the sampledValuesTable table by defining its contents and how it's structured
 */
void initialize_table_sampledValuesTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_sampledValuesTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("sampledValuesTable",
                                                     netsnmp_table_array_helper_handler,
                                                     sampledValuesTable_oid,
                                                     sampledValuesTable_oid_len,
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_sampledValuesTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: sampledValueID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = sampledValuesTable_COL_MIN;
    table_info->max_column = sampledValuesTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = sampledValuesTable_get_value;
    cb.container = netsnmp_container_find("sampledValuesTable_primary:"
                                          "sampledValuesTable:"
                                          "table_container");
#ifdef sampledValuesTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("sampledValuesTable_custom:"
                                                       "sampledValuesTable:"
                                                       "table_container"));
    cb.container->next->compare = sampledValuesTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_sampledValuesTable",
                "Registering table sampledValuesTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * sampledValuesTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int sampledValuesTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    sampledValuesTable_context *context = (sampledValuesTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_SAMPLEDVALUEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->sampledValueID,
                                 sizeof(context->sampledValueID));
        break;

    case COLUMN_RELATEDSAMPLEVALUE:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->relatedSampleValue,
                                 sizeof(context->relatedSampleValue));
        break;

    case COLUMN_SAMPLETYPE:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->sampleType,
                                 sizeof(context->sampleType));
        break;

    case COLUMN_SAMPLERECORDEDVALUE:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->sampleRecordedValue,
                                 sizeof(context->sampleRecordedValue));
        break;

    case COLUMN_NOFSAMPLEDVALUES:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->nOfSampledValues,
                                 sizeof(context->nOfSampledValues));
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "sampledValuesTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * sampledValuesTable_get_by_idx
 */
const sampledValuesTable_context *
sampledValuesTable_get_by_idx(netsnmp_index *hdr)
{
    return (const sampledValuesTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated sampledValuesTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
sampledValuesTable_context *sampledValuesTable_create_row(netsnmp_index *hdr, sampledStruct *req)
{
    sampledValuesTable_context *ctx = SNMP_MALLOC_TYPEDEF(sampledValuesTable_context);
    if (!ctx)
        return NULL;
    if (sampledValuesTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = req->sampledValueID;
    ctx->index.len = 1;
    ctx->sampledValueID = (long unsigned int)req->sampledValueID;
    ctx->relatedSampleValue = (long unsigned int)req->relatedSampleValue;
    ctx->sampleType = req->sampleType;
    ctx->sampleRecordedValue = req->sampleRecordedValue;
    ctx->nOfSampledValues = (long unsigned int)req->nOfsampledValues;

    printf("SampledValue inserida: %ld\n", ctx->sampledValueID);
    return ctx;
}
/**
 * the *_extract_index routine
 *
 * This routine is called when a set request is received for an index
 * that was not found in the table container. Here, we parse the oid
 * in the the individual index components and copy those indexes to the
 * context. Then we make sure the indexes for the new row are valid.
 */
int sampledValuesTable_extract_index(sampledValuesTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     *
     * extract index uses varbinds (netsnmp_variable_list) to parse
     * the index OID into the individual components for each index part.
     */
    netsnmp_variable_list var_sampledValueID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if ((hdr->len > MAX_OID_LEN) ||
            snmp_clone_mem((void *)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid)))
        {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /*
     * initialize variable that will hold each component of the index.
     * If there are multiple indexes for the table, the variable_lists
     * need to be linked together, in order.
     */
    memset(&var_sampledValueID, 0x00, sizeof(var_sampledValueID));
    var_sampledValueID.type = ASN_UNSIGNED; /* type hint for parse_oid_indexes */
                                            /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "sampledValuesTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_sampledValueID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_sampledValueID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy index components into the context structure
        */
        ctx->sampledValueID = *var_sampledValueID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_sampledValueID.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_sampledValueID);

    return err;
}