/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "commandTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid commandTable_oid[] = {commandTable_TABLE_OID};
const size_t commandTable_oid_len = OID_LENGTH(commandTable_oid);
/*Simple function that removes all spaces from a string*/
void remove_spaces(char *s)
{
    const char *d = s;
    do
    {
        while (*d == ' ')
            ++d;
    } while (*s++ = *d++);
}
/*This function will delete a commandTable entry based on the id*/
int deleteCommandEntry(long unsigned int id)
{
    commandTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = id;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
    {
        /*Remove from container first*/
        CONTAINER_REMOVE(cb.container, &index);
        /*Free commandTable_context*/
        commandTable_delete_row(ctx);
    }
    else
    {
        return 2;
    }
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
        return 1;
    else
        return 0;
}
/*This function will check all entries on commandTable, when an entry is found it will validate it, 
build a CAN message based on it's contents and then transmit it, finally, it will delete the entry 
If validation fails or message transmission failed for any reason a new error entry will be created on 
errorTable and the entry will be deleted*/
void checkActuators()
{
    netsnmp_iterator *it;
    void *data;
    it = CONTAINER_ITERATOR(cb.container);
    int res = 0;
    int s;
    struct sockaddr_can addr;
    struct ifreq ifr;
    struct can_frame frame;

    if ((s = socket(PF_CAN, SOCK_RAW, CAN_RAW)) < 0)
    {
        perror("Socket");
        exit;
    }

    strcpy(ifr.ifr_name, "vcan0");
    ioctl(s, SIOCGIFINDEX, &ifr);

    memset(&addr, 0, sizeof(addr));
    addr.can_family = AF_CAN;
    addr.can_ifindex = ifr.ifr_ifindex;
    if (bind(s, (struct sockaddr *)&addr, sizeof(addr)) < 0)
    {
        perror("Bind");
        exit;
    }
    if (NULL == it)
    {
        exit;
    }
    for (data = ITERATOR_FIRST(it); data; data = ITERATOR_NEXT(it))
    {
        commandTable_context *req = data;
        commandTemplateTable_context *temp = getTemplateEntry(req->templateID);
        if (temp != NULL)
        {
            /*Template exists, create CAN message based on this template*/
            unsigned char *message = malloc(sizeof(unsigned char) * temp->commandTemplate_len);
            /*Clear spaces from template*/
            remove_spaces(temp->commandTemplate);
            strcpy(message, temp->commandTemplate);
            unsigned char *input = malloc(sizeof(unsigned char) * 5);
            sprintf(input, "%04lX", (unsigned long)req->commandInput & 0xFFFF);
            /*TODO:Check if commandInput is valid for the target Node
            int insert = addError(req->commandUser, 11);
            if (insert != 0)
                printf("Error Insertion failed\n");
            */
            /*Create CAN message*/
            for (int i = 0, j = 0; i < strlen(message) && j < strlen(input); i++)
            {
                if (message[i] == '*')
                {
                    message[i] = input[j];
                    j++;
                }
            }
            free(input);
            /*CAN message created, send it to CAN network*/
            frame.can_id = strtoul(temp->targetNode, NULL, 16);
            frame.can_dlc = strlen(temp->commandTemplate) / 2;
            long unsigned int aux = strtoul(message, NULL, 16);
            printf("Command sent: %s %lX\n", temp->targetNode, aux);
            memcpy(frame.data, &aux, sizeof(aux));
            if (write(s, &frame, sizeof(struct can_frame)) != sizeof(struct can_frame))
            {
                perror("Write");
                exit;
            }

            /*TODO: Check if node received the message, if not create error entry
            int insert = addError(req->commandUser, 12);
            if (insert != 0)
                printf("Error Insertion failed\n");
            */
            /*Delete entry*/
            int delete = deleteCommandEntry(req->commandID);
            if (delete == 1)
                printf("Deletion of commandEntry failed\n");
            else if (delete == 2)
                printf("commandDataEntry not found\n");
            free(message);
        }
        else
        {
            /*TemplateID does not exist, create error and delete entry*/
            int insert = addError(req->commandUser, 10);
            if (insert != 0)
                printf("Error Insertion failed\n");
            int delete = deleteCommandEntry(req->commandID);
            if (delete == 1)
                printf("Deletion of commandEntry failed\n");
            else if (delete == 2)
                printf("commandDataEntry not found\n");
        }
    }
    ITERATOR_RELEASE(it);
    if (close(s) < 0)
    {
        perror("Close");
        exit;
    }
}
#ifdef commandTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int commandTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
commandTable_cmp(const void *lhs, const void *rhs)
{
    commandTable_context *context_l =
        (commandTable_context *)lhs;
    commandTable_context *context_r =
        (commandTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "commandTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
commandTable_context *
commandTable_get(const char *name, int len)
{
    commandTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "commandTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif
/************************************************************
 * Initializes the commandTable module
 */
void init_commandTable(void)
{
    initialize_table_commandTable();
}

/**
 * the *_extract_index routine
 *
 * This routine is called when a set request is received for an index
 * that was not found in the table container. Here, we parse the oid
 * in the the individual index components and copy those indexes to the
 * context. Then we make sure the indexes for the new row are valid.
 */
int commandTable_extract_index(commandTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     *
     * extract index uses varbinds (netsnmp_variable_list) to parse
     * the index OID into the individual components for each index part.
     */
    netsnmp_variable_list var_commandID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if ((hdr->len > MAX_OID_LEN) ||
            snmp_clone_mem((void *)&ctx->index.oids, hdr->oids,
                           hdr->len * sizeof(oid)))
        {
            return -1;
        }
        ctx->index.len = hdr->len;
    }

    /*
     * initialize variable that will hold each component of the index.
     * If there are multiple indexes for the table, the variable_lists
     * need to be linked together, in order.
     */
    memset(&var_commandID, 0x00, sizeof(var_commandID));
    var_commandID.type = ASN_UNSIGNED; /* type hint for parse_oid_indexes */
                                       /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "commandTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_commandID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_commandID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy index components into the context structure
        */
        ctx->commandID = *var_commandID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( *var_commandID.val.integer != XXX ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_commandID);

    return err;
}

/************************************************************
 * the *_can_delete routine is called to determine if a row
 * can be deleted.
 *
 * return 1 if the row can be deleted
 * return 0 if the row cannot be deleted
 */
int commandTable_can_delete(commandTable_context *undo_ctx,
                            commandTable_context *row_ctx,
                            netsnmp_request_group *rg)
{

    /*
     * TODO: check for other deletion requirements here
     */
    return 1;
}

/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index *commandTable_delete_row(commandTable_context *ctx)
{
    /* netsnmp_mutex_destroy(ctx->lock); */
    /*
    if (ctx->index.oids)
        free(ctx->index.oids);
    */
    free(ctx->data);

    /*
     * release header
     */
    free(ctx);

    return NULL;
}

/************************************************************
 * RESERVE is used to check the syntax of all the variables
 * provided, that the values being set are sensible and consistent,
 * and to allocate any resources required for performing the SET.
 * After this stage, the expectation is that the set ought to
 * succeed, though this is not guaranteed. (In fact, with the UCD
 * agent, this is done in two passes - RESERVE1, and
 * RESERVE2, to allow for dependancies between variables).
 *
 * BEFORE calling this routine, the agent will call duplicate_row
 * to create a copy of the row (unless this is a new row; i.e.
 * row_created == 1).
 *
 * next state -> SET_RESERVE2 || SET_FREE
 */
void commandTable_set_reserve1(netsnmp_request_group *rg)
{
    commandTable_context *row_ctx =
        (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx =
        (commandTable_context *)rg->undo_info;
    netsnmp_variable_list *var;
    netsnmp_request_group_item *current;
    int rc;

    /*
     * TODO: loop through columns, check syntax and lengths. For
     * columns which have no dependencies, you could also move
     * the value/range checking here to attempt to catch error
     * cases as early as possible.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /* or possibly 'netsnmp_check_vb_int_range' */
            rc = netsnmp_check_vb_uint(var);

            break;

        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /* or possibly 'netsnmp_check_vb_int_range' */
            rc = netsnmp_check_vb_uint(var);

            break;
        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            /* or possibly 'netsnmp_check_vb_int_range' */
            rc = netsnmp_check_vb_int(var);
            break;
        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            /* or possibly 'netsnmp_check_vb_type_and_size' */
            rc = netsnmp_check_vb_type_and_max_size(var, ASN_OCTET_STR,
                                                    sizeof(row_ctx->commandUser));
            break;
        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column in "
                              "commandTable_set_reserve1\n");
        }

        if (rc)
            netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
        rg->status = SNMP_MAX(rg->status, current->ri->status);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

void commandTable_set_reserve2(netsnmp_request_group *rg)
{
    commandTable_context *row_ctx = (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx = (commandTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;
    netsnmp_variable_list *var;
    int rc;

    rg->rg_void = rg->list->ri;

    /*
     * TODO: loop through columns, check for valid
     * values and any range constraints.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;
        rc = SNMP_ERR_NOERROR;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;
        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;
        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( *var->val.integer != XXX ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;
        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            /*
                     * TODO: routine to check valid values
                     *
                     * EXAMPLE:
                     *
                    * if ( XXX_check_value( var->val.string, XXX ) ) {
                *    rc = SNMP_ERR_INCONSISTENTVALUE;
                *    rc = SNMP_ERR_BADVALUE;
                * }
                */
            break;
        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }

        if (rc)
            netsnmp_set_mode_request_error(MODE_SET_BEGIN, current->ri, rc);
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * Assuming that the RESERVE phases were successful, the next
 * stage is indicated by the action value ACTION. This is used
 * to actually implement the set operation. However, this must
 * either be done into temporary (persistent) storage, or the
 * previous value stored similarly, in case any of the subsequent
 * ACTION calls fail.
 *
 * In your case, changes should be made to row_ctx. A copy of
 * the original row is in undo_ctx.
 */
void commandTable_set_action(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    commandTable_context *row_ctx = (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx = (commandTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * TODO: loop through columns, copy varbind values
     * to context structure for the row.
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            row_ctx->commandID = *var->val.integer;
            break;
        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            row_ctx->templateID = *var->val.integer;
            break;
        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            row_ctx->commandInput = *var->val.integer;
            break;
        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            memcpy(row_ctx->commandUser, var->val.string, var->val_len);
            row_ctx->commandUser_len = var->val_len;
            break;
        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
    /*
     * TODO: if you have dependencies on other tables, this would be
     * a good place to check those, too.
     */
}

/************************************************************
 * Only once the ACTION phase has completed successfully, can
 * the final COMMIT phase be run. This is used to complete any
 * writes that were done into temporary storage, and then release
 * any allocated resources. Note that all the code in this phase
 * should be "safe" code that cannot possibly fail (cue
 * hysterical laughter). The whole intent of the ACTION/COMMIT
 * division is that all of the fallible code should be done in
 * the ACTION phase, so that it can be backed out if necessary.
 *
 * BEFORE calling this routine, the agent will update the
 * container (inserting a row if row_created == 1, or removing
 * the row if row_deleted == 1).
 *
 * AFTER calling this routine, the agent will delete the
 * undo_info.
 */
void commandTable_set_commit(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    commandTable_context *row_ctx = (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx = (commandTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;
        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;
        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            break;

        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}

/************************************************************
 * If either of the RESERVE calls fail, the write routines
 * are called again with the FREE action, to release any resources
 * that have been allocated. The agent will then return a failure
 * response to the requesting application.
 *
 * AFTER calling this routine, the agent will delete undo_info.
 */
void commandTable_set_free(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    commandTable_context *row_ctx = (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx = (commandTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            break;

        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;

        default: /** We shouldn't get here */
            break;
            /** should have been logged in reserve1 */
        }
    }
}

/************************************************************
 * If the ACTION phase does fail (for example due to an apparently
 * valid, but unacceptable value, or an unforeseen problem), then
 * the list of write routines are called again, with the UNDO
 * action. This requires the routine to reset the value that was
 * changed to its previous value (assuming it was actually changed),
 * and then to release any resources that had been allocated. As
 * with the FREE phase, the agent will then return an indication
 * of the error to the requesting application.
 *
 * BEFORE calling this routine, the agent will update the container
 * (remove any newly inserted row, re-insert any removed row).
 *
 * AFTER calling this routing, the agent will call row_copy
 * to restore the data in existing_row from the date in undo_info.
 * Then undo_info will be deleted (or existing row, if row_created
 * == 1).
 */
void commandTable_set_undo(netsnmp_request_group *rg)
{
    netsnmp_variable_list *var;
    commandTable_context *row_ctx = (commandTable_context *)rg->existing_row;
    commandTable_context *undo_ctx = (commandTable_context *)rg->undo_info;
    netsnmp_request_group_item *current;

    /*
     * loop through columns
     */
    for (current = rg->list; current; current = current->next)
    {

        var = current->ri->requestvb;

        switch (current->tri->colnum)
        {

        case COLUMN_COMMANDID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_TEMPLATEID:
            /** UNSIGNED32 = ASN_UNSIGNED */
            break;

        case COLUMN_COMMANDINPUT:
            /** INTEGER = ASN_INTEGER */
            break;

        case COLUMN_COMMANDUSER:
            /** OCTET STRING = ASN_OCTET_STR */
            break;
        default:               /** We shouldn't get here */
            netsnmp_assert(0); /** why wasn't this caught in reserve1? */
        }
    }

    /*
     * done with all the columns. Could check row related
     * requirements here.
     */
}
commandTable_context *commandTable_create_row(netsnmp_index *hdr)
{
    commandTable_context *ctx = SNMP_MALLOC_TYPEDEF(commandTable_context);
    if (!ctx)
        return NULL;
    if (commandTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->commandUser_len = 0;
    return ctx;
}
/************************************************************
 *
 * Initialize the commandTable table by defining its contents and how it's structured
 */
void initialize_table_commandTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_commandTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("commandTable",
                                                     netsnmp_table_array_helper_handler,
                                                     commandTable_oid,
                                                     commandTable_oid_len,
                                                     HANDLER_CAN_RWRITE);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_commandTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: commandID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = commandTable_COL_MIN;
    table_info->max_column = commandTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = commandTable_get_value;
    cb.container = netsnmp_container_find("commandTable_primary:"
                                          "commandTable:"
                                          "table_container");
#ifdef commandTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("commandTable_custom:"
                                                       "commandTable:"
                                                       "table_container"));
    cb.container->next->compare = commandTable_cmp;
#endif
    cb.can_set = 1;
    cb.duplicate_row = (UserRowMethod *)commandTable_duplicate_row;
    cb.delete_row = (UserRowMethod *)commandTable_delete_row;
    cb.row_copy = (Netsnmp_User_Row_Operation *)commandTable_row_copy;
    cb.can_delete = (Netsnmp_User_Row_Action *)commandTable_can_delete;
    cb.create_row = (UserRowMethod *)commandTable_create_row;
    cb.set_reserve1 = commandTable_set_reserve1;
    cb.set_reserve2 = commandTable_set_reserve2;
    cb.set_action = commandTable_set_action;
    cb.set_commit = commandTable_set_commit;
    cb.set_free = commandTable_set_free;
    cb.set_undo = commandTable_set_undo;
    DEBUGMSGTL(("initialize_table_commandTable",
                "Registering table commandTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * commandTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int commandTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    commandTable_context *context = (commandTable_context *)item;
    switch (table_info->colnum)
    {

    case COLUMN_COMMANDID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->commandID,
                                 sizeof(context->commandID));
        break;
    case COLUMN_TEMPLATEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->templateID,
                                 sizeof(context->templateID));
        break;

    case COLUMN_COMMANDINPUT:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->commandInput,
                                 sizeof(context->commandInput));
        break;
    case COLUMN_COMMANDUSER:
        /** OCTET STRING = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->commandUser,
                                 context->commandUser_len);
        break;
    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "commandTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * commandTable_get_by_idx
 */
const commandTable_context *
commandTable_get_by_idx(netsnmp_index *hdr)
{
    return (const commandTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_duplicate row routine
 */
commandTable_context *
commandTable_duplicate_row(commandTable_context *row_ctx)
{
    commandTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(commandTable_context);
    if (!dup)
        return NULL;

    if (commandTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}
/************************************************************
 * the *_row_copy routine
 */
int commandTable_row_copy(commandTable_context *dst, commandTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;

    /*
     * copy components into the context structure
     */
    dst->commandID = src->commandID;
    dst->templateID = src->templateID;
    dst->commandInput = src->commandInput;
    memcpy(dst->commandUser, src->commandUser, src->commandUser_len);
    dst->commandUser_len = src->commandUser_len;
    return 0;
}