/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "requestControlDataTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid requestControlDataTable_oid[] = {requestControlDataTable_TABLE_OID};
const size_t requestControlDataTable_oid_len = OID_LENGTH(requestControlDataTable_oid);
/*This function will delete an entry from requestControlDataTable*/
int deleteControlEntry(int id){
    requestControlDataTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = id;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
    {
        CONTAINER_REMOVE(cb.container,&index);
        requestControlDataTable_delete_row(ctx);
    }else{
        return 2;
    }
    ctx = CONTAINER_FIND(cb.container, &index);
    if(ctx)
        return 1;
    else
        return 0;
}
/*This function will add a requestStruct to the snmp agent*/
int insertControlRow(requestStruct *req){
    requestControlDataTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = req->reqID;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    ctx = NULL;
    /* Search for it first. */
    ctx = CONTAINER_FIND(cb.container, &index);
    if (ctx)
    {
        CONTAINER_REMOVE(cb.container,&index);
        requestControlDataTable_delete_row(ctx);
        ctx = requestControlDataTable_create_row(&index, req);
        CONTAINER_INSERT(cb.container, ctx);
        return 0;
    }else{
        ctx = requestControlDataTable_create_row(&index, req);
        CONTAINER_INSERT(cb.container, ctx);
        return 0;
    }
    return 1;
}

/*Given an ID, this function will return a row with that ID*/
void* getControlTableID(long unsigned int id){
    netsnmp_index index;
    oid index_oid[2];
    index_oid[0] = id;
    index.oids = (oid *)&index_oid;
    index.len = 1;
    void *data=CONTAINER_FIND(cb.container,&index);
    return data;
}
#ifdef requestControlDataTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int requestControlDataTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
requestControlDataTable_cmp(const void *lhs, const void *rhs)
{
    requestControlDataTable_context *context_l =
        (requestControlDataTable_context *)lhs;
    requestControlDataTable_context *context_r =
        (requestControlDataTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "requestControlDataTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
requestControlDataTable_context *
requestControlDataTable_get(const char *name, int len)
{
    requestControlDataTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "requestControlDataTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the requestControlDataTable module
 */
void init_requestControlDataTable(void)
{
    initialize_table_requestControlDataTable();
}

/************************************************************
 *
 * Initialize the requestControlDataTable table by defining its contents and how it's structured
 */
void initialize_table_requestControlDataTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_requestControlDataTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("requestControlDataTable",
                                                     netsnmp_table_array_helper_handler,
                                                     requestControlDataTable_oid,
                                                     requestControlDataTable_oid_len,
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_requestControlDataTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: requestControlID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = requestControlDataTable_COL_MIN;
    table_info->max_column = requestControlDataTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = requestControlDataTable_get_value;
    cb.container = netsnmp_container_find("requestControlDataTable_primary:"
                                          "requestControlDataTable:"
                                          "table_container");
#ifdef requestControlDataTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("requestControlDataTable_custom:"
                                                       "requestControlDataTable:"
                                                       "table_container"));
    cb.container->next->compare = requestControlDataTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_requestControlDataTable",
                "Registering table requestControlDataTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * requestControlDataTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int requestControlDataTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    requestControlDataTable_context *context = (requestControlDataTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_REQUESTCONTROLID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->requestControlID,
                                 sizeof(context->requestControlID));
        break;

    case COLUMN_GENERICREQUESTCONTROLTYPEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->genericRequestControlTypeID,
                                 sizeof(context->genericRequestControlTypeID));
        break;

    case COLUMN_SETTINGMODE:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->settingMode,
                                 sizeof(context->settingMode));
        break;

    case COLUMN_COMMITTIME:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->commitTime,
                                 context->commitTime_len);
        break;

    case COLUMN_WAITTIME:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->waitTime,
                                 context->waitTime_len);
        break;

    case COLUMN_ENDCONTROLTIME:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->endControlTime,
                                 context->endControlTime_len);
        break;

    case COLUMN_DURATIONCONTROLTIME:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->durationControlTime,
                                 context->durationControlTime_len);
        break;

    case COLUMN_EXPIRECONTROLTIME:
        /** OBUDateandTime = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->expireControlTime,
                                 context->expireControlTime_len);
        break;

    case COLUMN_VALUESTABLEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->valuesTableID,
                                 sizeof(context->valuesTableID));
        break;

    case COLUMN_VALUESID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->valuesID,
                                 sizeof(context->valuesID));
        break;

    case COLUMN_STATUSCONTROL:
        /** INTEGER = ASN_INTEGER */
        snmp_set_var_typed_value(var, ASN_INTEGER,
                                 (char *)&context->statusControl,
                                 sizeof(context->statusControl));
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "requestControlDataTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * requestControlDataTable_get_by_idx
 */
const requestControlDataTable_context *
requestControlDataTable_get_by_idx(netsnmp_index *hdr)
{
    return (const requestControlDataTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated requestControlDataTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
requestControlDataTable_context *requestControlDataTable_create_row(netsnmp_index *hdr, requestStruct *req)
{
    requestControlDataTable_context *ctx = SNMP_MALLOC_TYPEDEF(requestControlDataTable_context);
    if (!ctx)
        return NULL;
    if (requestControlDataTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = req->reqID;
    ctx->index.len = 1;
    ctx->requestControlID = (long unsigned int)req->reqID;
    ctx->genericRequestControlTypeID = (long unsigned int)req->genericID;
    ctx->settingMode = req->settingMode;
    strcpy(ctx->commitTime, req->commitTime);
    ctx->commitTime_len = strlen(req->commitTime);
    strcpy(ctx->waitTime, req->waitTime);
    ctx->waitTime_len = strlen(req->waitTime);
    strcpy(ctx->endControlTime, req->endTime);
    ctx->endControlTime_len = strlen(req->endTime);
    strcpy(ctx->durationControlTime, req->duration);
    ctx->durationControlTime_len = strlen(req->duration);
    strcpy(ctx->expireControlTime, req->expireTime);
    ctx->expireControlTime_len = strlen(req->expireTime);
    ctx->valuesTableID = (long unsigned int)req->valuesTable;
    ctx->valuesID = (long unsigned int)req->valueID;
    ctx->statusControl = req->status;
    return ctx;
}

/*
 * the *_extract_index routine
 * Não sei se esta função esta funcional
 */
int requestControlDataTable_extract_index(requestControlDataTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_requestControlID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if (snmp_clone_mem((void *)&ctx->index.oids, hdr->oids, sizeof(oid)))
        {
            return -1;
        }
    }

    /**
     * Create variable to hold each component of the index
     */
    memset(&var_requestControlID, 0x00, sizeof(var_requestControlID));
    var_requestControlID.type = ASN_GAUGE;
    /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "requestControlDataTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_requestControlID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_requestControlID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy components into the context structure
        */
        /** skipping external index requestControlID */
        if (var_requestControlID.val_len > sizeof(ctx->requestControlID))
            err = -1;
        else
            ctx->requestControlID = (long unsigned int)var_requestControlID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( XXX_check_value( var_requestControlID.val, XXX ) ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_requestControlID);

    return err;
}
/************************************************************
 * the *_duplicate row routine
 */
requestControlDataTable_context *
requestControlDataTable_duplicate_row(requestControlDataTable_context *row_ctx)
{
    requestControlDataTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(requestControlDataTable_context);
    if (!dup)
        return NULL;

    if (requestControlDataTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}
/************************************************************
 * the *_row_copy routine
 */
int requestControlDataTable_row_copy(requestControlDataTable_context *dst, requestControlDataTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;

    /*
     * copy components into the context structure
     */
    dst->requestControlID = src->requestControlID;
    dst->genericRequestControlTypeID = src->genericRequestControlTypeID;
    dst->settingMode = src->settingMode;

    memcpy(dst->commitTime, src->commitTime, src->commitTime_len);
    dst->commitTime_len = src->commitTime_len;
    memcpy(dst->waitTime, src->waitTime, src->waitTime_len);
    dst->waitTime_len = src->waitTime_len;
    memcpy(dst->endControlTime, src->endControlTime, src->endControlTime_len);
    dst->endControlTime_len = src->endControlTime_len;
    memcpy(dst->durationControlTime, src->durationControlTime, src->durationControlTime_len);
    dst->durationControlTime_len = src->durationControlTime_len;
    memcpy(dst->expireControlTime, src->expireControlTime, src->expireControlTime_len);
    dst->expireControlTime_len = src->expireControlTime_len;
    dst->valuesTableID = src->valuesTableID;
    dst->valuesID = src->valuesID;
    dst->statusControl = src->statusControl;
    return 0;
}
/************************************************************
 * the *_delete_row method is called to delete a row.
 */
netsnmp_index *requestControlDataTable_delete_row(requestControlDataTable_context *ctx)
{
    /* netsnmp_mutex_destroy(ctx->lock); */
    /*
    if (ctx->index.oids)
        free(ctx->index.oids);
    */
    free(ctx->data);

    /*
     * TODO: release any memory you allocated here...
     */

    /*
     * release header
     */
    free(ctx);

    return NULL;
}