/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.array-user.conf
 *
 *
 * For help understanding NET-SNMP in general, please check the 
 *     documentation and FAQ at:
 *
 *     http://www.net-snmp.org/
 *
 *
 * For help understanding this code, the agent and how it processes
 *     requests, please check the following references.
 *
 *     http://www.net-snmp.org/tutorial-5/
 *
 *
 * You can also join the #net-snmp channel on irc.freenode.net
 *     and ask for help there.
 *
 *
 * And if all else fails, send a detailed message to the developers
 *     describing the problem you are having to:
 *
 *    net-snmp-coders@lists.sourceforge.net
 *
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "commandTemplateTable.h"

static netsnmp_handler_registration *my_handler = NULL;
static netsnmp_table_array_callbacks cb;

const oid commandTemplateTable_oid[] = {commandTemplateTable_TABLE_OID};
const size_t commandTemplateTable_oid_len = OID_LENGTH(commandTemplateTable_oid);

#ifdef commandTemplateTable_CUSTOM_SORT
/************************************************************
 * keep binary tree to find context by name
 */
static int commandTemplateTable_cmp(const void *lhs, const void *rhs);

/************************************************************
 * compare two context pointers here. Return -1 if lhs < rhs,
 * 0 if lhs == rhs, and 1 if lhs > rhs.
 */
static int
commandTemplateTable_cmp(const void *lhs, const void *rhs)
{
    commandTemplateTable_context *context_l =
        (commandTemplateTable_context *)lhs;
    commandTemplateTable_context *context_r =
        (commandTemplateTable_context *)rhs;

    /*
     * check primary key, then secondary. Add your own code if
     * there are more than 2 keys
     */
    int rc;

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR,
             "commandTemplateTable_compare not implemented! Container order undefined\n");
    return 0;
#endif

    /*
     * EXAMPLE (assuming you want to sort on a name):
     *   
     * rc = strcmp( context_l->xxName, context_r->xxName );
     *
     * if(rc)
     *   return rc;
     *
     * TODO: fix secondary keys (or delete if there are none)
     *
     * if(context_l->yy < context_r->yy) 
     *   return -1;
     *
     * return (context_l->yy == context_r->yy) ? 0 : 1;
     */
}

/************************************************************
 * search tree
 */
/** TODO: set additional indexes as parameters */
commandTemplateTable_context *
commandTemplateTable_get(const char *name, int len)
{
    commandTemplateTable_context tmp;

    /** we should have a custom container */
    netsnmp_assert(cb.container->next != NULL);

    /*
     * TODO: implement compare. Remove this ifdef code and
     * add your own code here.
     */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "commandTemplateTable_get not implemented!\n");
    return NULL;
#endif

    /*
     * EXAMPLE:
     *
     * if(len > sizeof(tmp.xxName))
     *   return NULL;
     *
     * strncpy( tmp.xxName, name, sizeof(tmp.xxName) );
     * tmp.xxName_len = len;
     *
     * return CONTAINER_FIND(cb.container->next, &tmp);
     */
}
#endif

/************************************************************
 * Initializes the commandTemplateTable module
 */
void init_commandTemplateTable(void)
{
    commandTemplateTable_context *ctx;
    netsnmp_index index;
    oid index_oid[2];
    initialize_table_commandTemplateTable();
    FILE *fp;
    char *line = NULL;
    size_t len = 0;
    ssize_t read;
    int i = 0, k = 0;
    char *token;
    fp = fopen("././Files/template.txt", "r");
    if (fp == NULL)
    {
        printf("ERROR FILE NOT FOUND\n");
        exit(EXIT_FAILURE);
    }
    while ((read = getline(&line, &len, fp)) != -1)
    {
        if (i > 0)
        {
            if (line[strlen(line) - 1] == '\n')
                line[strlen(line) - 1] = '\0';
            const char sep[2] = ":";
            char *token;
            token = strtok(line, sep);
            int aux = 0;
            char *descr;
            char *target;
            char *template;
            while (token != NULL)
            {
                if (aux == 0)
                {
                    descr = malloc(sizeof(char) * strlen(token));
                    strcpy(descr, token);
                }
                if (aux == 1)
                {
                    target = malloc(sizeof(char) + strlen(token));
                    strcpy(target, token);
                }
                if (aux == 2)
                {
                    template = malloc(sizeof(char) * strlen(token));
                    strcpy(template, token);
                }
                aux++;
                token = strtok(NULL, sep);
            }
            index_oid[0] = k;
            index.oids = (oid *)&index_oid;
            index.len = 1;
            ctx = NULL;
            /* Search for it first. */
            ctx = CONTAINER_FIND(cb.container, &index);
            if (!ctx)
            {
                // No dice. We add the new row
                ctx = commandTemplateTable_create_row(&index, descr, k, target, template);
                CONTAINER_INSERT(cb.container, ctx);
                k++;
            }
        }
        i++;
    }
    fclose(fp);
    if (line)
        free(line);
}

/************************************************************
 *
 * Initialize the commandTemplateTable table by defining its contents and how it's structured
 */
void initialize_table_commandTemplateTable(void)
{
    netsnmp_table_registration_info *table_info;

    if (my_handler)
    {
        snmp_log(LOG_ERR, "initialize_table_commandTemplateTable_handler called again\n");
        return;
    }

    memset(&cb, 0x00, sizeof(cb));

    /** create the table structure itself */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    my_handler = netsnmp_create_handler_registration("commandTemplateTable",
                                                     netsnmp_table_array_helper_handler,
                                                     commandTemplateTable_oid,
                                                     commandTemplateTable_oid_len,
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info)
    {
        snmp_log(LOG_ERR, "malloc failed in "
                          "initialize_table_commandTemplateTable_handler\n");
        return; /** mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    /*
     * TODO: add any external indexes here.
     */

    /*
     * internal indexes
     */
    /** index: commandTemplateID */
    netsnmp_table_helper_add_index(table_info, ASN_UNSIGNED);

    table_info->min_column = commandTemplateTable_COL_MIN;
    table_info->max_column = commandTemplateTable_COL_MAX;

    /***************************************************
     * registering the table with the master agent
     */
    cb.get_value = commandTemplateTable_get_value;
    cb.container = netsnmp_container_find("commandTemplateTable_primary:"
                                          "commandTemplateTable:"
                                          "table_container");
#ifdef commandTemplateTable_CUSTOM_SORT
    netsnmp_container_add_index(cb.container,
                                netsnmp_container_find("commandTemplateTable_custom:"
                                                       "commandTemplateTable:"
                                                       "table_container"));
    cb.container->next->compare = commandTemplateTable_cmp;
#endif
    DEBUGMSGTL(("initialize_table_commandTemplateTable",
                "Registering table commandTemplateTable "
                "as a table array\n"));
    netsnmp_table_container_register(my_handler, table_info, &cb,
                                     cb.container, 1);
}

/************************************************************
 * commandTemplateTable_get_value
 *
 * This routine is called for get requests to copy the data
 * from the context to the varbind for the request. If the
 * context has been properly maintained, you don't need to
 * change in code in this fuction.
 */
int commandTemplateTable_get_value(
    netsnmp_request_info *request,
    netsnmp_index *item,
    netsnmp_table_request_info *table_info)
{
    netsnmp_variable_list *var = request->requestvb;
    commandTemplateTable_context *context = (commandTemplateTable_context *)item;

    switch (table_info->colnum)
    {

    case COLUMN_COMMANDTEMPLATEID:
        /** UNSIGNED32 = ASN_UNSIGNED */
        snmp_set_var_typed_value(var, ASN_UNSIGNED,
                                 (char *)&context->commandTemplateID,
                                 sizeof(context->commandTemplateID));
        break;

    case COLUMN_COMMANDDESCRIPTIONID:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->commandDescription,
                                 context->commandDescription_len);
        break;

    case COLUMN_TARGETNODE:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->targetNode,
                                 context->targetNode_len);
        break;

    case COLUMN_COMMANDTEMPLATE:
        /** OCTETSTR = ASN_OCTET_STR */
        snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                 (char *)&context->commandTemplate,
                                 context->commandTemplate_len);
        break;

    default: /** We shouldn't get here */
        snmp_log(LOG_ERR, "unknown column in "
                          "commandTemplateTable_get_value\n");
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/************************************************************
 * commandTemplateTable_get_by_idx
 */
const commandTemplateTable_context *
commandTemplateTable_get_by_idx(netsnmp_index *hdr)
{
    return (const commandTemplateTable_context *)
        CONTAINER_FIND(cb.container, hdr);
}
/************************************************************
 * the *_create_row routine is called by the table handler
 * to create a new row for a given index. If you need more
 * information (such as column values) to make a decision
 * on creating rows, you must create an initial row here
 * (to hold the column values), and you can examine the
 * situation in more detail in the *_set_reserve1 or later
 * states of set processing. Simple check for a NULL undo_ctx
 * in those states and do detailed creation checking there.
 *
 * returns a newly allocated commandTemplateTable_context
 *   structure if the specified indexes are not illegal
 * returns NULL for errors or illegal index values.
 */
commandTemplateTable_context *commandTemplateTable_create_row(netsnmp_index *hdr, char *descr, int id, char *target, char *template)
{
    commandTemplateTable_context *ctx = SNMP_MALLOC_TYPEDEF(commandTemplateTable_context);
    if (!ctx)
        return NULL;
    if (commandTemplateTable_extract_index(ctx, hdr))
    {
        free(ctx->index.oids);
        free(ctx);
        return NULL;
    }
    ctx->index.oids = ctx->oid_buf;
    ctx->oid_buf[0] = id;
    ctx->index.len = 1;
    ctx->commandTemplateID = (long unsigned int)id;
    strcpy(ctx->commandDescription, descr);
    ctx->commandDescription_len = strlen(descr);
    strcpy(ctx->targetNode, target);
    ctx->targetNode_len = strlen(target);
    strcpy(ctx->commandTemplate, template);
    ctx->commandTemplate_len = strlen(template);
    return ctx;
}

/*
 * the *_extract_index routine
 */
int commandTemplateTable_extract_index(commandTemplateTable_context *ctx, netsnmp_index *hdr)
{
    /*
     * temporary local storage for extracting oid index
     */
    netsnmp_variable_list var_commandTemplateID;
    int err;

    /*
     * copy index, if provided
     */
    if (hdr)
    {
        netsnmp_assert(ctx->index.oids == NULL);
        if (snmp_clone_mem((void *)&ctx->index.oids, hdr->oids, sizeof(oid)))
        {
            return -1;
        }
    }

    /**
     * Create variable to hold each component of the index
     */
    memset(&var_commandTemplateID, 0x00, sizeof(var_commandTemplateID));
    var_commandTemplateID.type = ASN_GAUGE;
    /** TODO: link this index to the next, or NULL for the last one */
#ifdef TABLE_CONTAINER_TODO
    snmp_log(LOG_ERR, "commandTemplateTable_extract_index index list not implemented!\n");
    return 0;
#else
    var_commandTemplateID.next_variable = NULL;
#endif

    /*
     * parse the oid into the individual components
     */
    err = parse_oid_indexes(hdr->oids, hdr->len, &var_commandTemplateID);
    if (err == SNMP_ERR_NOERROR)
    {
        /*
        * copy components into the context structure
        */
        /** skipping external index commandTemplateID */
        if (var_commandTemplateID.val_len > sizeof(ctx->commandTemplateID))
            err = -1;
        else
            ctx->commandTemplateID = (long unsigned int)var_commandTemplateID.val.integer;

        /*
            * TODO: check index for valid values. For EXAMPLE:
            *
              * if ( XXX_check_value( var_commandTemplateID.val, XXX ) ) {
          *    err = -1;
          * }
          */
    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_commandTemplateID);

    return err;
}
/************************************************************
 * the *_duplicate row routine
 */
commandTemplateTable_context *
commandTemplateTable_duplicate_row(commandTemplateTable_context *row_ctx)
{
    commandTemplateTable_context *dup;

    if (!row_ctx)
        return NULL;

    dup = SNMP_MALLOC_TYPEDEF(commandTemplateTable_context);
    if (!dup)
        return NULL;

    if (commandTemplateTable_row_copy(dup, row_ctx))
    {
        free(dup);
        dup = NULL;
    }

    return dup;
}
/************************************************************
 * the *_row_copy routine
 */
int commandTemplateTable_row_copy(commandTemplateTable_context *dst, commandTemplateTable_context *src)
{
    if (!dst || !src)
        return 1;

    /*
     * copy index, if provided
     */
    if (dst->index.oids)
        free(dst->index.oids);
    if (snmp_clone_mem((void *)&dst->index.oids, src->index.oids,
                       src->index.len * sizeof(oid)))
    {
        dst->index.oids = NULL;
        return 1;
    }
    dst->index.len = src->index.len;
    dst->commandTemplateID = src->commandTemplateID;
    memcpy(dst->commandDescription, src->commandDescription, src->commandDescription_len);
    dst->commandDescription_len = src->commandDescription_len;
    memcpy(dst->targetNode, src->targetNode, src->targetNode_len);
    dst->targetNode_len = src->targetNode_len;
    memcpy(dst->commandTemplate, src->commandTemplate, src->commandTemplate_len);
    dst->commandTemplate_len = src->commandTemplate_len;

    return 0;
}